### ISSUE TITLE
키타산블랙 및 사토노다이아몬드 이미지 추가

### ISSUE THREAD

**Issue by sanyav1** [sanyav1/Umamusume-KR-Resetmarathon#10]

**Comment by nyqui** [comment]
키타산: 
https://ac-p2.namu.la/20220725sac/c0d2f75819093ef447363100545b3a84ad03a977bd06d65edf9e9487c0f02539.png

**Comment by nyqui** [comment]
사토노:
https://ac.namu.la/20220725sac/653a7eb18bb658cba2013224172c7ea81de273f176538d5b6374094d7f7df7bc.png

**Comment by sanyav1** [comment]
> 사토노: https://ac.namu.la/20220725sac/653a7eb18bb658cba2013224172c7ea81de273f176538d5b6374094d7f7df7bc.png
> 키타산: https://ac-p2.namu.la/20220725sac/c0d2f75819093ef447363100545b3a84ad03a977bd06d65edf9e9487c0f02539.png

추가하려고 이슈 만들어뒀는데 감사하네요. 잘 추가해둘게요.
