### ISSUE TITLE
연동 및 게스트계정 선택화면에서 networkError 메시지 후 진행불가

### ISSUE THREAD

**Issue by grommel435** [sanyav1/Umamusume-KR-Resetmarathon#16]
![Cap 2022-07-25 18-37-44-711](https://user-images.githubusercontent.com/13380278/180746956-27c30809-17ea-4a0f-ab2f-4ae4c216e0e8.jpg)
에러가 발생하는 화면

![Cap 2022-07-25 18-37-02-079](https://user-images.githubusercontent.com/13380278/180746893-1eb5c814-0154-4b54-b9fd-9cbe593265b2.png)
에러 발생 시 로그

해당 상태에서 STOP 누른 후 수동으로 게스트선택 시 정상적으로 진행 가능함
STOP 후 다시 START 눌러도 동일한 상태로 정지

**Comment by sanyav1** [comment]
이미지맥스가 맛이 간 것 같은데, 이미지맥스와 블루스택을 작업관리자로 끄고 다시 시작해보시고, PC 재부팅 뒤에도 문제가 있나 확인해주세요.

**Comment by sanyav1** [comment]
확인. 버그가 아님. LoopstepOr 수행 과정에서 나오는 메시지
