### ISSUE TITLE
불러온 뒤 문자 인코딩 깨짐

### ISSUE THREAD

**Issue by dudu555** [sanyav1/Umamusume-KR-Resetmarathon#20]
![dhodlfo](https://user-images.githubusercontent.com/109961691/180770175-dd7e4971-5562-45ad-b353-65dfad8df212.JPG)
https://arca.live/b/umamusume/55064822?category=%EA%B3%B5%EB%9E%B5%2F%EC%A0%95%EB%B3%B4&p=1   여기에있는 파일에다가 깃허브에있는 noip버전 붙여넣기했는디 그러면 안되는거임?

**Comment by kestr31** [comment]
인코딩 문제인데 해결법 찾는 중

**Comment by sanyav1** [comment]
해결완료. noip 브랜치의 prescript의 인코딩이 깨진거였음. 수정사항 반영됨.
