### ISSUE TITLE
내가 정말 초보라 그러는데.... 설명이 이해가 좀...(미안)

### ISSUE THREAD

**Issue by wolf28254125** [sanyav1/Umamusume-KR-Resetmarathon#21]
저번 버전까지 잘 썼어 IP 버전으로 그에 따라 이번 버전 쓸려고 하니.

1. IP 버전으로 깔면 한글이 안됨
2. 디폴트로 까니 되긴 함. 근데 ADB 폴더가 없어서 전처럼 ADB 명령어를 쓸 수가 없음
3. ADB랑 한글 안되는 거 어떻게 해야 하는 거야? 다들 리세하다 IP 막히면 멈추는 건가?

설명보고 다 따라 하는데.... 컴맹이지만 열심히 하고 디버깅도 다 해서 분명 저번 버전을 잘만 썼는데...
이번에는 뭔가 안풀리네...

**Comment by sanyav1** [comment]
아까 한글 깨지는거 수정된거 확인했는데 지금 다시 받아서 해본 거야?

디폴트라는건 뭘 말하는 것인지 모르겠네. ADB 폴더는 ImageMax Core에 있어.

**Comment by wolf28254125** [comment]
> 

디폴트에서 받은 건 안깨지는 너가 디폴트(개발버전) IP, NO IP 올려놨자낭, 메인 버전은 안깨는 데 IP는 깨지더라구 이미지맥스 코어에 왜 없을까 나는.... 구글 에서 다시 받아볼게

**Comment by wolf28254125** [comment]
지금도 IP 버전은 꺠지고 MAIN버전은 안깨진다. MAIN버전 써도 IP 갱신이 되려나?

**Comment by wolf28254125** [comment]
ADB는 찾았어 카페꺼 쓰면 안되고 구글 링크 쓴 버전은 있구나

**Comment by sanyav1** [comment]
아 카페에서 바로 받아써서 그렇구나. 그건 생각도 못했다. 고마워 이건 언급해야겠다.
