### ISSUE TITLE
도감 보상 받고 40연차째 들어가게 만들기

### ISSUE THREAD

**Issue by sanyav1** [sanyav1/Umamusume-KR-Resetmarathon#3]

**Comment by darkimbers** [comment]
오후10시에 noIp branch 로 하고 있는데, 도감 보상 받는 행위를 안하는 게 맞는건가요 ?? 
아직 이슈만 적어두시고, commit 은 안하신 건가 해서요 'ㅁ'

**Comment by sanyav1** [comment]
네 Closed되지 않은 것은 아직 작성 중이거나  작성을 안해서 커밋이 안된거고, Closed 된 것들은 Main 브랜치에 반영된거에요

**Comment by darkimbers** [comment]
Main은 IP 기능을 사용하는 버전이던데..으으...테더링 안했다고 실행이 안되다보니.Main을 쓸수가없어요 ..

**Comment by sanyav1** [comment]
main은 개발을 하는 과정에 있는 브랜치니까 어쩔 수 없어요. 어느 정도 필요하다 판단되는 기능을 넣어서 태그를 달 때 다른 버전에 통합할거라서 기다려주시는거 말곤 답이 없겠네요.
